# .travis.yml, for "Travis CI" – metadata of Apps®.
# Continuous Integration (CI) is a development practice that requires developers to integrate code into a shared repository several times a day.
# Each check-in is then verified by an automated build, allowing teams to detect problems early.
# @require  : Grunt/Node.js®/NPM
# @author   : Prabhat Kumar, http://prabhatkumar.org/.
